### ISSUE TITLE
Wemos TFT 1.4" shield

### ISSUE THREAD

**Issue by OslafEman** [G6EJD/Wemos-1.4TFT-Shield-Examples#1]
Hi, I hope you'll can help me.  I'm working now with MH ET Live mini and some Wemos D1 mini' shields.  I don't know about electronics and currently I'm learning to use these amazing devices.
In my project I connected a 1.4" TFT shield in the stacked way and it works well, but when I connect it using the TFT I2C connector shield and the TFT cable (all of them bought in the official store) the screen sets on but don't display anything.
I tried with two TFT shields and three connector cables without success.
Am I missing something?  There is not forum o web site where this information is given and the store doesn't respond me.
I'm a follower of your videos and your ESP32-ESP8266-File-Download-Upload-Delete-Stream-and-Directory code was very helpful, besides that I saw your video regarding this shield.
Thanks in advance.
Oslaf

**Comment by G6EJD** [comment]
You need to use this:
![esp32-tft-lcd](https://user-images.githubusercontent.com/6075568/49577604-a3227380-f93f-11e8-9f25-f9a0bd8375b3.jpg)
Set your display pins in the code to match the CS, RTS and DC. 
I do-not know what you are using at the ESP32 end? A wemos D32 pro with a connector on-board?

**Comment by OslafEman** [comment]
Thanks David, I'm using a "MH ET Live mini ESP32" with the Wemos D1 mini shields.  The TFT display works fine if it is stacked, as you can see here. 
![captura6](https://user-images.githubusercontent.com/43764333/49592036-17f4ae00-f93e-11e8-9522-7481adf90050.PNG)
I need to use a non-stacked connection, so I use a TFT/I2C connector shield (https://www.aliexpress.com/store/product/TFT-I2C-Connector-Shield-V1-1-0-for-LOLIN-WEMOS-D1-mini-1x-TFT-2x-I2C/1331105_32846977179.html?spm=a2g1y.12024536.productList_2559252.subject_1)
In the connector shield I redirected the TFT_CS from pin 0 to pin 4 to match the screen configuration, but even so it doesn't work.  The screen gets on but doesn't display anything.
As I don't know electronics I would like to avoid complicated wiring, soldering, etc., and keep using the stacking shields.
This is the kind of connections I'd like to use.
![captura5](https://user-images.githubusercontent.com/43764333/49594891-d4517280-f944-11e8-8915-07900eecb911.PNG)

Oslaf

**Comment by G6EJD** [comment]
OK, thanks the photos' helped a lot with the understanding of the issue.
 #define TFT_CS     14 
 #define TFT_RST    33
 #define TFT_DC     27
 Adafruit_ST7735 tft = Adafruit_ST7735(TFT_CS,  TFT_DC, TFT_RST); 

In the code definition it is assumed the SPI Bus is connected to the display, which on the MH-T Live is like this:
TFT Shield   -   MHT-LIVE
Pin1 - NC
Pin2 to MHT GPIO14
Pin3 to MHT 3.3v
Pin4 to MHT GPIO18
Pin5 NC
Pin6 to MHT GPIO23
Pin7 to MHT GPIO27
Pin8 to MHT GPIO33
Pin9 to MHT Gnd
Pin10 to MHT GPIO32

Pin10 is adjacent to the CH340 and Pin1 is next to the ESP32

We know the display will work when stacked onto an MHT-Live ESP32 but as delivered that shield (TFT plus I2C) has no connection for example  between TFT_RST and either D1, D3 or D4, you have to choose, similarly for CD and LED. To help clarify, check it out with a DVM where e.g. RST is going, there are solder pads on the rear to choose with a solder bridge.

**Comment by G6EJD** [comment]
TFT Connector
    1    TFT_LED    Backlight control pin, default: NC
    2    GND
    3    TFT_RST   TFT RESET pin, default: RST
    4    TFT_DC     TFT Register select pin, default: D8 (IO15)
    5    MOSI        SPI MOSI, D7 (IO13)
    6    MISO        SPI MISO, D6 (IO12)
    7    SCK          SPI SCK, D5 (IO14)
    8    3V3
    9    TFT_CS    TFT Select pin, default: D0 (IO16)
    10    TS_CS    Touch Screen Select pin, default: D3 (IO0)

    I2C Connector
    1    3V3
    2    SCL    D1 (IO5)
    3    SDA    D2 (IO4)
    4    GND

    User IO Connector
    1    3V3
    2    D4 (IO2)
    3    D3 (IO0)
    4    GND

**Comment by G6EJD** [comment]
I've been going through the Lolin/Wemos wiki for the display shield and the code I published for the ESP32 has the correct pin definitions, the only pin not connected is the LED power source which is no connected on the rear of the shield, the TFT_DC is connected to GPIO17 and the TFT_CS connected to GPIO16 but crucially TFT_LED is not connected, I suggest connecting it to say 3.3v as a test while the MHT Live is trying to display something.

**Comment by OslafEman** [comment]
Hi David, thank you very much. Your help guided me in the way of the solution. Finally I have succeeded connecting the 1.4" TFT shield using the TFT/I2C connector shield and the TFT cable.
Fortunately I didn't need to do soldering or wiring, just a little modification in the code.
![captura1](https://user-images.githubusercontent.com/43764333/49681578-55f2ee80-fa72-11e8-96b6-f579267538f7.PNG)
(Apilada = stacked).
For the MH ET Live Mini the Wemos 1.4" shield works according the previous image in both modes just changing the pin numbers.
I apologize for my poor English.  

Oslaf

**Comment by G6EJD** [comment]
Good to hear it’s working. It would have been better if Wemos (now Lolin) had used the same pins for this connector so that it all worked seamlessly.
